### ISSUE TITLE
Fix bumpver issue

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-client#556]
A recent use of bumpver (to create 1.3.6a0) was bugged, as it also replaced some dependencies' versions: https://github.com/fractal-analytics-platform/fractal-client/commit/1fb10f6785c849849fa95de8a4923fb3eac72aa6.

To review.

**Comment by tcompa** [comment]
Temporarily fixed with b654461.
Let's update things so that this won't happen again.

**Comment by tcompa** [comment]
This is due to `file_patterns` matching strings `version = "1.2.3"`, which now do appear in pyproject (as of docs-dependencies pinning) - e.g. in
```toml
mkdocstrings = { extras = ["python"], version = "0.22.0" }
mkdocs-include-markdown-plugin = { version = "4.0.4", python = "^3.8,<3.12" }
```

The quick fix is to add a linebreak (`$`) to the regex, see 15ba046.
