### ISSUE TITLE
Review dependabot config

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-client#608]
Goal: an action which runs once per week and opens a PR with an updated `poetry.lock`, but without modifying `pyproject.toml`.
I tried to setup dependabot configuration in `.github/dependabot.yml`:
```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "lockfile-only"
    schedule:
      interval: "weekly"
```
but it does not propose any update - see https://github.com/fractal-analytics-platform/fractal-client/network/updates/780502809.

---

We can either fix dependabot, or write a tiny custom action that:
- sets up poetry
- runs `poetry update`
- creates a new PR with a branch where the new `poetry.lock` was committed
